### ISSUE TITLE
[Rewards] We have too many color variations for Reward Items

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#230]
![image](https://cloud.githubusercontent.com/assets/17926293/22861241/51ab7b3a-f114-11e6-88f4-2bbb6599218b.png)

At the moment we have 20 color variation/combination for each of the 30 items, for a total of 600 possible combinations (that is 570 Small Rewards because a color variation is unlocked together when we unlock an item).
But following  the Reward Unlock table we unlock "only" 340 Small Rewards (2 per each PS).
In order to solve this incoherence we can:
- reduce the number of color variation/combination (i.e. with 13 colors per item we would have 360 Small Rewards)
- unlock 3 Small Rewards per Play Session (instead of 2), giving a reward also for the 1-star score (reaching 510 Small Rewards overall)
- use a combination of the 2 options above

We have to define soon how to proceed with this issue...

**Comment by StefanoCecere** [comment]
since now we are unlocking ALL colors since day 0, i guess this discussion isn't needed anymore..
