### ISSUE TITLE
[PlaySessions] Some PS make MissingLetter and similar games fail

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#293]
For example: at PS 3.1.7:

[laughed: ضَحِكَ  dad_fathah, hah_kasrah, kaf_fathah, ]

Fathah appears at 4.1.1
Kashrah appare nel 4.3.1

So the teacher gives up.

**Comment by StefanoCecere** [comment]
with the new curriculum, this issue can be closed
