### ISSUE TITLE
[Player Icon] it would be cool to "highlight" the Player Icon if he reached 3-stars in all unlocked PS

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#426]
The only incentive we have for the player to reach 3-stars is unlocking more color variations for Antura customization... it's ok, but it may not be enough.
Now that we have a cool Player Icon/Avatar, we may want to "highlight" it if the player reached 3-stars in all unlocked PS (i.e. if he reached PS 1.1.100 he must have reached 3-stars in PS 1.1.1 and PS 1.1.2).

Higlight could be done with JapRays behind the Icon and it could be "communicated/explained" in the PS Reward Screen replacing the bones counter (bottom-left) with the Player Icon that "highlights" when the bar reaches 3-stars.

It's not a simple change because it will require to modify the Player Icon and several scenes (Start, Map, PlaySession Result)... we should thnk it well before making this change!

**Comment by StefanoCecere** [comment]
we have the ALL STARS highlight in the player icon and the map has been reworked. closing this!
