### ISSUE TITLE
[Color tickle]  letters alpha issue on Huawei

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#430]
Testing on my Huawei p9 plus with android marshmallow and there is an issue with the alpha.
![screenshot_2017-03-12-12-13-22](https://cloud.githubusercontent.com/assets/8046715/23830973/c8f5a244-071f-11e7-80b3-2c6ec55a8ca5.png)

**Comment by StefanoCecere** [comment]
closing since we don't have new feedback
