### ISSUE TITLE
buttons: always avoid double clicks

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#444]
maybe disabling buttons interactivity at first valid click?
we have to avoid absolutely double actions!

**Comment by Demigiant** [comment]
Going to add a toggle to the button's inspector to set it as "one shot" (meaning it will become non-interactable after beign clicked, until it's disabled and re-enabled or re-created).
**By default the "one shot" toggle will be unselected.**

**Comment by StefanoCecere** [comment]
uhm.. so it meanh that we should have the UI_button on EVERY button i nthe game, right?

**Comment by Demigiant** [comment]
Yup, I implemented the new OneShot option and committed it, now I'm checking around to see where it needs to be added (if there are buttons that are not a UIButton but don't need the OneShot I'll skip them)

**Comment by Demigiant** [comment]
P.S. I already toggle OneShot to TRUE for all continue/restart/close buttons of the globalUI

**Comment by Demigiant** [comment]
Ok seems that every button that needs it has it, and I set the OneShot also on Antura's button in the Map. If you need to set it for others you have the option in the UIButton (or MenuButton) Inspector. I remove myself from the issue but leave it open

**Comment by Demigiant** [comment]
Actually, I close it :P

**Comment by FrancyCavallari** [comment]
Play in the Map (touching Antura or the marker) must be One Shot, otherwise you skip the game Selector.

**Comment by CatmanIta** [comment]
Fixed in [cb6f9d5]
