### ISSUE TITLE
[First Contact] You can start playing without having entered the Antura Space

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#454]
1. Create a new profile
2. At the end of the Intro you reach the map and you are asked to press on the Antura button (top-right)
3. Instead press the Pause button (top-left) and quit
4. Play again the same profile
5. The intro scene is launched again
6. At the end of the Intro you reach the Map and you have completed the First contact without entering the Antura Space

**Comment by StefanoCecere** [comment]
closing since new FirstContactManager...
