### ISSUE TITLE
[Minigames] the bones-bar should fill everytime a round has been completed successfully

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#458]
NOTE: this bug is present in several minigames (i.e. Maze).
Let's say that a minigame has 6 rounds and we use the following rule:
- 0 successful rounds > 0 bones
- 1 or 2 rounds > 1 bone
- 3 or 4 rounds > 2 bones
- 5 or 6 rounds > 3 bones 

The bar should behave like this:
- 0 rounds > empty
- 1 round > filled until the first bone
- 2 rounds > filled until 1.5 bones (in the middle between the first and the second bone)
- 3 bones > filled until the second bone
etc...

**Comment by StefanoCecere** [comment]
is this issue still alive? @FrancyCavallari ?

**Comment by davidebarbieri** [comment]
ThrowBalls,
Maze,
MixedLetters,
MakeFriends,
Balloons
