### ISSUE TITLE
[Android] A user reported an issue with his review

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#473]
![image](https://cloud.githubusercontent.com/assets/17926293/25104489/d20090ac-23c0-11e7-9168-26fb9b9ed03b.png)

**Comment by StefanoCecere** [comment]
we can't do much about this, but hope the new Unity version fixes.
eventually in the future we'll update to Unity 5.6. i close this issue for now

**Comment by FrancyCavallari** [comment]
Ok, BTW, since the user gave 3-stars maybe he meant that the loading time was very long (instead of neverending) :-)
