### ISSUE TITLE
[Reward Screen] You can continue without seeing the reward you got

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#474]
The current sequence is the following:

1. Once the lock opens, Antura appears and comes close to the camera.
2. Once Antura reaches it's central position (close to the camera) the PLAY/CONTINUE button appears.
3. After that Antura rotates to the correct angle and the Reward appears on him

If I touch the PLAY button as soon as it appears (step 2) I don't see the Reward.

>>> Better delay the appearance of the PLAY button after the Reward has been revealed

**Comment by CatmanIta** [comment]
Fixed
