### ISSUE TITLE
Version 1.0.5 compiles but throws a dozen error messages when played

### ISSUE THREAD

**Issue by ZiadJ** [vgwb/Antura_arabic#483]
Here's a screenshot for the start scene:

![image](http://i.imgur.com/aBr9fl3.png)
The game only partially works at this point with the introductory audio and animations playing fine but the only interaction that seem to work are clicking on Antura for various animations and clicking on the settings button.

Lots of warnings showing up as well:

![image](http://i.imgur.com/S2rxjAB.png)

**Comment by StefanoCecere** [comment]
hi @ZiadJ as i wrote in the #programming channel time ago, al ldeveloeprs should downlaod a fresh new clone of this repository.
i guess you just did update the old one.
if you still will have problems, get back here with more details!

**Comment by ZiadJ** [comment]
I'm using the code from yesterday's commit and  made sure the project type set to Android but I'm still getting the same errors.

**Comment by ZiadJ** [comment]
Well I'm now using yesterday's commit from the master branch and made sure the project type is set to Android but I'm still getting the same errors. I tried updating TextMeshPro to the latest version from the Asset Store. Is there anything else I might have missed?

**Comment by StefanoCecere** [comment]
hi @ZiadJ i just did a fresh download and import, and it works perfectly (just a warning on a 3d model)

are you sure you are using Unity 5.5.4?
you don't have to import anything else (Textmesh Pro is alredy in the project)

**Comment by ZiadJ** [comment]
I'm using Unity 2017.1 RC1 right now, just because I was curious about Timeline, after I tried the Dev branch on Unity 5.6.1 on another machine a few weeks ago. They both broke with the same issues but yeah it could have something to do with versioning. Are you planning to upgrade anytime soon?

I know about Texmesh Pro being there already but I thought I'd re-import it still since the current binaries are from an earlier release.

**Comment by StefanoCecere** [comment]
ahhh good. 2017.1 isn't supported (i didn't make a test)
i can tell you that 5.6.1 works quite good (but you have to update TextmeshPro because there are several versions.. and we have embedded the one compatible with Unity 5.5)

so: or you download Unity 5.5.4, or use 5.6.2 and update TextmeshPro (i tested these)

**Comment by ZiadJ** [comment]
Unfortunately I'm still getting more or less the same errors somehow even after I downloaded the code from the [master branch ](https://github.com/vgwb/Antura_arabic/archive/master.zip). I also made sure I'm using Unity 5.6.2(f1) this time and updated Text Mesh Pro before running. Not sure if that can help but just before I updated TMPro this error message showed up as well: 
> An assembly with the same name 'TextMeshPro-1.0.55.55.0b10' has already been imported. Consider removing one of the references or sign the assembly Assets/Standard Assets/TextMesh Pro/Plugins/TextMeshPro-1.0.55.55.0b10.dll (Location of the symbol related to previous error) Assets/Standard Assets/TextMesh Pro/Plugins/Runtime DLL/TextMeshPro-1.0.55.55.0b10.dll (location of the symbol related to previous error

Anyway I can still try to reuse some of your assets even though I'm not able to run it right now. I'd like to thank you for the great work you're sharing here guys.

**Comment by StefanoCecere** [comment]
@ZiadJ the current project is working fine with Unity 5.5.x
we'll update to a newer Unity version in next months.. stay tuned!

ciao!
