### ISSUE TITLE
[Fast Crowd- Counting] Wrong numbers 

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#488]
AppVersion 1.0.7b6 , platform: Windows

In fast crowd counting the first number on the floor is 1 that worked only with the ZERO LL, in the attached image the ONE LL is accepted for the 2 on the drop zone. 

Call from the cheat window and play fast crowd counting. 

![fcc](https://user-images.githubusercontent.com/8046715/28060308-724ee79c-662f-11e7-9c75-42237d58d16a.png)
![fcc_0](https://user-images.githubusercontent.com/8046715/28060309-72503e76-662f-11e7-9ed4-0de68cdff65f.png)

**Comment by CatmanIta** [comment]
Fixed. Bug was with FastCrowd requesting numbered words without skipping the 'zero' word. 
Note that Balloons works correctly instead as it starts from ZERO.
