### ISSUE TITLE
[UI/UX] From the RewardScene, access the Antura Space

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#492]
From the RewardScene, access the Antura Space

**Comment by CatmanIta** [comment]
The button should appear after the unlock animation is performed (like the 'continue' button does).
The button should NOT appear during first contact.

**Comment by CatmanIta** [comment]
Implemented. In need of UI/UX.

**Comment by FrancyCavallari** [comment]
The First Contact is a special case that bring yous automatically to the Antura Space: we must define how the UI should behave in that case in order to be coherent with the rest of the game.

**Comment by Demigiant** [comment]
Fixed UI and animated entrance. Note that the button throws an error when pressed, but I guess you know that already :P Leaving this issue open just to be on the safe side.

**Comment by CatmanIta** [comment]
That's just because I guess you clicked it after loading the scene directly instead of getting to the scene after a reward is actually obtained. No problem there!

I noticed that the Antura Space button appear a while after the continue button, wouldn't that push the player to click continue fast instead of looking at what is happening and what he has unlocked?

**Comment by Demigiant** [comment]
Antura Space Button now appears together with the Continue button
