### ISSUE TITLE
Repeat button after minigame play

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#493]
Let the player repeat a minigame when it ends.

**Comment by CatmanIta** [comment]
When a minigame ends, the player is shown the choice to continue or to repeat the current minigame. 
This is in need of UI.

**Comment by CatmanIta** [comment]
Issue: what happens to the bones that are collected at the end of the game? 
Can the player collect multiple bones with more retries? Or should we only count the bones if he actually clicks 'Continue'?

**Comment by CatmanIta** [comment]
It was decided that bones are always collected.

**Comment by FrancyCavallari** [comment]
As a General Rule, every time you complete a game and you are shown the 0-3 Bones result the Bones are added to your profile! This way even if you play a game from the "book/minigame selector" you can collect bones.

**Comment by Demigiant** [comment]
(inside GlobalUI)

**Comment by Demigiant** [comment]
Done and replaced in GlobalUI

**Comment by CatmanIta** [comment]
I don't see a difference with the button I added, I'm not sure if it is ok, as the 'continue' button is animated while the 'retry' is not!

**Comment by Demigiant** [comment]
[Make appearance animation]

**Comment by Demigiant** [comment]
Done
