### ISSUE TITLE
[Credits] Update Credits list with latest team members

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#496]
Add Thiago (Data Analyst)
Review if any other change is needed

**Comment by StefanoCecere** [comment]
Thiago added d11d3029dc550d9f887327f29902e236a86d49e9

**Comment by FrancyCavallari** [comment]
Emmanuel created a credit V5 in the folder and put modifications for TH Koln and their partners

**Comment by FrancyCavallari** [comment]
I still have to review the VGWB part...

**Comment by FrancyCavallari** [comment]
The updated Credits are available here (with changes highlighted in colors):
https://docs.google.com/document/d/1c_OmNFmiyAjhElebk51DcFWLwaNP7YRYJmH5zUM-8dQ/edit?usp=sharing

**Comment by FrancyCavallari** [comment]
I spotted another mistake...
... ARABIC COPYWRITING  was wrongly spelled (marked in RED in the doc)
