### ISSUE TITLE
feature: Bones Shop

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#498]
- [x] definitive list of Shop's items  
- [x] create icons  
- [x] create final objects+scale+positions  
- [x] review buttons states (pressed) UI

**Comment by CatmanIta** [comment]
There is a problem with the current design. If the button list is scrollable, then the 'dragging' actions won't work (such as throwing a bone or the ball).

**Comment by CatmanIta** [comment]
https://docs.google.com/presentation/d/1hc5Sjzq6cg_Y-FHgIK819KzfHWOG0KF9jhPh6Klf4Ww/edit?usp=drivesdk
