### ISSUE TITLE
[Daily Rewards] UI and Animations need to be finalized

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#509]
![image](https://user-images.githubusercontent.com/17926293/32415783-8634aeb0-c23f-11e7-913f-f64e5706dcec.png)
- TODAY button should be much bigger/highlighted than the other ones
- It's not clear that the player has to touch TODAY button (tutorial finger animation much sooner)
- Once touched, today bones should animate towards the Bone Counter

**Comment by CatmanIta** [comment]
Fixed (2)
Did half of (1) by making it larger.
Calling @Demigiant for (1) and (3)

**Comment by Demigiant** [comment]
Finalized
