### ISSUE TITLE
[Map] It's strange to have 2 identical Antura buttons with 2 different functions

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#513]
Just scroll the map and the "Find Antura" button will appear... and it's identical to the Antura Space one.
![image](https://user-images.githubusercontent.com/17926293/32416026-ed92b450-c242-11e7-8df5-82a6b79b1da8.png)

Maybe we can change the Antura Space button in order to have both Antura and a Bone Counter in the same icon: this way we have always the counter on screen (and we won't need the Bone Counter to appear when we find a hidden bone).
Or maybe you have a better proposal :-)

**Comment by FrancyCavallari** [comment]
Another option would be to replace the "Find Antura" Icon with a small Antura over the Yellow/Purple marker... or maybe the Marker alone...

**Comment by Demigiant** [comment]
Done, I made a new animated icon :P
