### ISSUE TITLE
[Map] Camera position "jumps" when entering with the Demo Profile

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#514]
1. create the Demo Profile
2. Enter the Map with the Demo Profile
3. Antura is centered on the Map
![image](https://user-images.githubusercontent.com/17926293/32416162-398ffbfe-c245-11e7-826a-761a0615dbc4.png)
4. touch anywhere to scroll and notice that the camera jumps instantaneously here
![image](https://user-images.githubusercontent.com/17926293/32416171-5e719194-c245-11e7-8f11-89aff71cdb6c.png)

**Comment by CatmanIta** [comment]
Fixed in [a8adde7]

**Comment by FrancyCavallari** [comment]
fixed
