### ISSUE TITLE
[Map] Finalize Layout and UI element

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#515]
- Several UI elements are still placeholders
- Antura is too small when far away (and so the Play button will be too small too)
![image](https://user-images.githubusercontent.com/17926293/32416235-8c68c2a6-c246-11e7-9566-fe25f1e5f2bc.png)
- some elements suffer from Z-fight (or something else) and disappear, like the stars below Antura in this screeshot
![image](https://user-images.githubusercontent.com/17926293/32416251-c149e626-c246-11e7-8d14-d6ae69cb5e06.png)
- the popup dialog is not clearly linked with the selected PS
- the Stage selector at the bottom is too small and needs a different solution... maybe we could reuse the same element we have in the book: 
![image](https://user-images.githubusercontent.com/17926293/32417467-7e015b38-c25a-11e7-8dd8-cbb86c42975b.png)

**Comment by FrancyCavallari** [comment]
The new (placeholder) Stage Selector is too small to be used on a phone:
![image](https://user-images.githubusercontent.com/17926293/32734993-da2f8b70-c893-11e7-8d9f-91149d9fdf2a.png)

**Comment by CatmanIta** [comment]
Enlarged indicators.
