### ISSUE TITLE
[Shop] Finalize UI Design & Art

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#524]
The system is working but we still have to define:
- the final list of Art assets we will use in the Shop and their price
- the UI elements for the shop

**Comment by FrancyCavallari** [comment]
UI is almost final but we should add more elements in the Shop... following the guidelines at page 16 of this doc: https://docs.google.com/presentation/d/19sutHrHhngMtgOh4g1XFEkh2MDKFM6GU_IJiX81-okI/edit?usp=sharing
PS: it would be cool to add more Floor and Background elements!

**Comment by FrancyCavallari** [comment]
Delete UI is still very WIP...
... when you drag an item, the Bin Icon appears correctly... 
![image](https://user-images.githubusercontent.com/17926293/35148081-33fa24e2-fd11-11e7-975b-90427c63ba38.png)
... but when you dop the item over the Bin Icon the confirmation popup is not OK
![image](https://user-images.githubusercontent.com/17926293/35148115-5aac16a4-fd11-11e7-86ee-eafc5c15ebfd.png)

1. The Bin Icon should stay visible (non-interactive) to reinforce that you are about to DELETE an item
2. The "Are you sure?" confirmation popup (with voice dialog) should appear instead of the purple V/X icons

**Comment by FrancyCavallari** [comment]
The items that you cannot buy should be DARK GRAY instead of RED.
We always used RED as a warning sign ... so it can be confusing. I.e. The Trash Bin Icon is RED and it's correct, since it's a warning.
![image](https://user-images.githubusercontent.com/17926293/35148403-4b00af66-fd12-11e7-9676-ab9695bc743e.png)

**Comment by FrancyCavallari** [comment]
When dragging an object the busy slots are shown in RED, again we should try using the DARK GRAY instead because RED sends a wrong warning message: there's no danger, simply the slot if busy and cannot be used.
![image](https://user-images.githubusercontent.com/17926293/35148518-ca5c60d4-fd12-11e7-98ed-8bb7f3554b21.png)

**Comment by FrancyCavallari** [comment]
We could allow closig the Shop Menu by touching Antura, like for the Customization Menu... but we have to disable it when a popup confirmation is present!

**Comment by FrancyCavallari** [comment]
The Photo Icon should become DARK GRAY when you don't have enough bones to buy it.
![image](https://user-images.githubusercontent.com/17926293/35148779-e200e81c-fd13-11e7-8688-a2d4fe1de886.png)

**Comment by FrancyCavallari** [comment]
When confirming a purchase the Bone Counter is visible (so you know how many bone you have) but if you press it it does nothing (except then playing the pressed anim)
![image](https://user-images.githubusercontent.com/17926293/35148862-39918348-fd14-11e7-9806-9ed76d86e7fc.png)
We may want to drive the player attention to the popup making it ALL bounce if you press the Bone Counter.

**Comment by FrancyCavallari** [comment]
Most of the button, (Bone Counter, confirmation V/X) , do not play any Sound FX when pressed!
They should all play the standard button SFX... except the Photo that should have a specific sound FX.

**Comment by FrancyCavallari** [comment]
One more thing: the "tree" and "mountains" slots are too close to camera... better move them further away.

**Comment by CatmanIta** [comment]
- Delete UI redone
- SFXs added
- Colors fixed
- Rearranged and reoriented slots

**Comment by FrancyCavallari** [comment]
let's review it when everything is finalized
