### ISSUE TITLE
[Shop] The Shop menu does not reappear after taking a picture

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#525]
Open the Shop menu and then take a picture...
... no matter if you confirm or not the picture, when the popup disappears the Shop menu does not reappear (and the Customization button is not present):
![image](https://user-images.githubusercontent.com/17926293/32418285-316b8ade-c267-11e7-9c60-0feb96c9edf8.png)

**Comment by CatmanIta** [comment]
Fixed in [3a11388]
