### ISSUE TITLE
[Daily Rewards] Design and integrate voice dialogs & audio fx

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#526]
Once the UI and animations will be completed we will define the needed voice dialogs and audio FX

**Comment by StefanoCecere** [comment]
meanwhile i jsut added a minimal sfx to the increasing bones

**Comment by FrancyCavallari** [comment]
voice dialogs are: 

DailyReward_Collect
DailyReward_ComeBack_1
DailyReward_ComeBack_2
DailyReward_Intro_1
DailyReward_Intro_2
