### ISSUE TITLE
[Map] a Pin is present on a lock session

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#529]
The first PS of each stage has a Pin over it even if locked.
Pin should not be present over a locked PS.
![image](https://user-images.githubusercontent.com/17926293/32687820-1f051fd8-c6c5-11e7-8a42-7cf59552dbfe.png)
![image](https://user-images.githubusercontent.com/17926293/32687825-394c35a2-c6c5-11e7-9ab8-1da5c7005758.png)

**Comment by CatmanIta** [comment]
Fixed in [43c8600]
