### ISSUE TITLE
[Map] The animated circle could always help the player to locate Antura

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#530]
When Antura is on screen, the animated circles below him help in driving the player attention...
![image](https://user-images.githubusercontent.com/17926293/32687855-d10a694a-c6c5-11e7-9cfe-f24ba52fc1f1.png)

... but when Antura is out of screen we only have the "Go To Antura" button (with no animation):
![image](https://user-images.githubusercontent.com/17926293/32687864-f6b4a6ce-c6c5-11e7-9696-09d7a657941f.png)

We may want to use a similar effect (animated circles) over the "Go To Antura" button to help the player!
NOTE: this issue is linked to #513.

**Comment by CatmanIta** [comment]
Sounds fine to me, leaving this to Daniele

**Comment by Demigiant** [comment]
I made the icon bounce, since it looked nicer there, and also made nicer arrows
