### ISSUE TITLE
[Map] when Go To Antura button is over a Pin the input "touches" also the Pin

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#531]
scroll the map in order to have the Go To Antura  button appear...
... and keep scrolling until it covers a Pin.
Touch the Go To Antura  button .
Notice that the camera goes to Antura...
... but Antura moves to the Pin that was below the button!

NOTE: it only happens on Device (I tested on iPad)... on PC it does not happen.

**Comment by FrancyCavallari** [comment]
It happens also on Android...

**Comment by CatmanIta** [comment]
Fixed (but untested!) in [c73258b]

This was an issue with how IsPointerOverGameObject works with mouse and fingers:

https://forum.unity.com/threads/ispointerovereventsystemobject-always-returns-false-on-mobile.265372/

**Comment by FrancyCavallari** [comment]
Still present, also for the AnturaSpace and X buttons
