### ISSUE TITLE
[Map] We could let the player touch the popup dialog to PLAY

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#532]
Right now we have a big popup dialog below Antura... but you have to touch Antura to play.
Maybe we could allow the player to touch ALSO the popup in order to PLAY the selected PS.
What do you think?

**Comment by FrancyCavallari** [comment]
NOTE: The final decision may also depend from the final look of the popup dialog.

**Comment by CatmanIta** [comment]
It really depends on the final look and where the popup is placed. I'd prefer having a single and unmistakable way to start the actual PS (i.e. the play button), so players can more easily understand what they are accessing.

**Comment by Demigiant** [comment]
I would make a dedicated interface as we talked about, and always use a single button as Michele says. Though this will need to be done when final map is in place, so we can see the actual available spaces.
