### ISSUE TITLE
[DailyReward] Consider letting the player skip to the next scene if he taps fast

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#534]
As of now, the player needs to wait after having collected the bones before he can go to the next scene.

I suggest to add a small delay after the first click (collecting bones) after which, if the player clicks again, the next scene is loaded directly.

**Comment by FrancyCavallari** [comment]
The new bones animation is pretty quick... but now there's a long delay (2 sec?) after the animation is over.
Better remove the delay.
About allowing the Skip, I would avoid it: kids tend to spam the touchscreen, better to be sure they see the anim and they understand what's happening.
