### ISSUE TITLE
[MiniGame] ColorTickle_letter

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#549]
- [ ] redo tutorial (now Alif but we don't have it in Stage 1)? or we can keep it anyway as it is or just change the Tutorial Sentence in something more generic

- [ ] check the tutorialState vs IntroductionState

- [x] now the noon is played severla time in 1.1.1 .. can we pass the numebr of rounds (5) to be played or make the rounds be set to the numebr of letters passed by the QUestionBUilder?

**Comment by FrancyCavallari** [comment]
- [ ] customize sensitivity to allow smaller kids to play easily (or increase the number of lives to allow them to win more easily)

- [ ] variable number of rounds ? Could be an option... or we could set it fixed to 5 rounds (the number of letters in Stage 1) if it's much simpler to implement.

**Comment by FrancyCavallari** [comment]
1. Use Beh instead of Alef for the tutorial
2. Instead of Variable Number of Rounds we can set the game to finish as soon as you reach 3 stars (usually 5 rounds) that is general rule for the game

**Comment by CatmanIta** [comment]
Added Beh instead of Alef in [20d0b54]

**Comment by CatmanIta** [comment]
Set the game to end when you reach 3 stars, tutorial improved in [5c3e8b3]
