### ISSUE TITLE
[FirstContact] Antura Space can get stuck if leaving/quitting in the middle of the Customization tutorial 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#572]
Create a profile, get the First Reward ...
... then follow the Customization Tutorial until when you are supposed to touch Antura.
Instead of completing the Tutorial, turn off/leave the game.
When you restart and reload the profile the game brings you to te Map (BUG: you should go directly to the Antura Space) and the it gets stuck after you open the customization Menu...
![image](https://user-images.githubusercontent.com/17926293/34642926-a71d9954-f31b-11e7-84fd-84c8a4fc74bb.png)

... giving the following exception :
```
Exception: No new category!
Antura.AnturaSpace.AnturaSpaceTutorialManager.<StepTutorialCustomization>m__1 () (at Assets/_app/_scripts/AnturaSpace/AnturaSpaceTutorialManager.cs:179)
Antura.AnturaSpace.AnturaSpaceTutorialManager+<WaitAndSpawnCO>c__Iterator0.MoveNext () (at Assets/_app/_scripts/AnturaSpace/AnturaSpaceTutorialManager.cs:439)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

```

**Comment by CatmanIta** [comment]
Fixing this gracefully would mean saving the 'is new' changes only after you exit the scene, but I think that since this is a minor problem I've just fakde it (selecting the first item).
Fixed in a5b119f
