### ISSUE TITLE
[FirstContact] When you reach the Map after the Antura Customization you can go back to Antura Space and the Shop is present

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#574]
When you reach the Map for the first time (after the Antura Customization)...
![image](https://user-images.githubusercontent.com/17926293/34643489-31e3032c-f325-11e7-8b96-994b840b67f5.png)
....you can go back to the Antura Space and you have this:
![image](https://user-images.githubusercontent.com/17926293/34643494-44062638-f325-11e7-898c-d7edf52e6134.png)

You should not be able to see the Shop and Photo before their tutorial!
If you can go back to the Antura Soace they must be hidden.

**Comment by CatmanIta** [comment]
Fixed in the latest commits
