### ISSUE TITLE
[Savegame] The warning should appear only if you have old profiles 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#575]
When you download the new version this warning message should appear ONLY IF you have profiles created with v1.0. Now it appears everytime you download a new version.
![image](https://user-images.githubusercontent.com/17926293/34648824-0dee201e-f3a2-11e7-8fc5-557151a31418.png)

**Comment by StefanoCecere** [comment]
i'll give a full review of this tomorrow

**Comment by StefanoCecere** [comment]
this was not urgent.. since it happens only when getting a new app version..
i don't way it's not to be fixed, but that it won't happen to our users untile they got 1.2.1

**Comment by FrancyCavallari** [comment]
Now the warning appears also if you have a clean device (no Antura version installed)...
... it should appear ONLY if you have old profiles.
