### ISSUE TITLE
[FirstContact] Creating a new Demo Profile does not complete the first contact

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#576]
Create a new Demo profile and load it.
Notice that you are positioned in PS 1.1.1...
![image](https://user-images.githubusercontent.com/17926293/34648859-ec5a80cc-f3a2-11e7-853f-ab487bbc411d.png)
... and the Unveal Book and Unveal GameLauncher tutorials are played one after the other:
![image](https://user-images.githubusercontent.com/17926293/34648871-1925c47c-f3a3-11e7-8b62-7d40839328f8.png)
![image](https://user-images.githubusercontent.com/17926293/34648877-7ba199a0-f3a3-11e7-8d36-6a11fb73edf2.png)

And in the Map the Stages and Pause button are missing.

**Comment by FrancyCavallari** [comment]
And if you enter the Antura Space you have no Exit button:
![image](https://user-images.githubusercontent.com/17926293/34648908-0aef094e-f3a4-11e7-85c8-39cf2c9ab793.png)

**Comment by CatmanIta** [comment]
Fixed in [b6dc222]
