### ISSUE TITLE
[Shop] You can get to negative bone counter!

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#577]
1. Go to the Shop.
2. Drag an item to the scene
3. Cancel the purchase
4. Drag it again
5. Confirm the purchase
6. Notice that the Item has costed you the double of its price!
(The cost of all canceled purchases is added to the next purchase)

![image](https://user-images.githubusercontent.com/17926293/34679900-b054065c-f497-11e7-9e4a-7b586a65db99.png)

**Comment by CatmanIta** [comment]
Fixed in [69ef3ff]

**Comment by FrancyCavallari** [comment]
The above case is solves... but same problem can happen if you:

1. Go to the Shop.
2. Drag an item to the scene... without getting close/highlighting any drop spot 
3. Cancel the purchase by dropping it far from any drop spot
4. Drag it again
5. Confirm the purchase
6. Notice that the Item has costed you the double of its price!
(The cost of all canceled purchases is added to the next purchase)

**Comment by CatmanIta** [comment]
Fixed, the bug was related to the tutorial's logic not allowing cancellations and thus never removing a few callbacks.
