### ISSUE TITLE
[Antura Space] the NEW star should not take into account "new" customization colors

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#578]
Enter the Antura Space:
Notice that the NEW star is on AnturaCustomization button:
![image](https://user-images.githubusercontent.com/17926293/34828872-407cfc22-f6df-11e7-84f8-79c86bb4b1f5.png)

If you click on the button you have the NEW Star over the category:
![image](https://user-images.githubusercontent.com/17926293/34828932-64a893cc-f6df-11e7-80b9-17c9381e216c.png)

If you enter on the Category you have nothing new !!! :-(
![image](https://user-images.githubusercontent.com/17926293/34828985-91fa0dc4-f6df-11e7-934e-391d47a16973.png)

The system is still taking into account UNUSED/NEW colors to set the NEW star over the previous buttons!

**Comment by CatmanIta** [comment]
Fixed in [2d52158]
