### ISSUE TITLE
[MakeFriends] When the right letter is dragged the letter should be highlighted in green on both Words

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#585]
this way we reinforce the understanding of the gameplay in the tutorial round and we reward better the player
![image](https://user-images.githubusercontent.com/17926293/34876377-7bc31b5a-f7a1-11e7-81e7-c3b428fab3b5.png)

**Comment by CatmanIta** [comment]
Issue seems to be related to **ArabicAlphabetHelper.FindLetter.**

MakeFriends  calls **ArabicAlphabetHelper.FindLetter(Core.AppManager.I.DB, word.Data, markedLetter.Data, true));**

I suspect that the arabic alphabet helper is not correctly finding the given letter with the correct form when splitting.

**Comment by FrancyCavallari** [comment]
I found a worning in the Log:
Cannot parse letter ّ (0651) in اَﻟﺰَّﻳْﺖ
UnityEngine.Debug:Log(Object)
Antura.Helpers.ArabicAlphabetHelper:AnalyzeArabicString(DatabaseObject, String, Boolean, Boolean) (at Assets/_app/_scripts/Language/ArabicAlphabetHelper.cs:299)
Antura.Helpers.ArabicAlphabetHelper:SplitWord(DatabaseManager, WordData, Boolean, Boolean) (at Assets/_app/_scripts/Language/ArabicAlphabetHelper.cs:138)
Antura.Helpers.ArabicAlphabetHelper:FindLetter(DatabaseManager, WordData, LetterData, Boolean) (at Assets/_app/_scripts/Language/ArabicAlphabetHelper.cs:120)
Antura.LivingLetters.LivingLetterController:MarkLetters(List`1, Color) (at Assets/_app/_scripts/LivingLetter/LivingLetterController.cs:473)
Antura.Minigames.MakeFriends.MakeFriendsLivingLetter:MarkLetters(List`1, Color) (at Assets/_games/MakeFriends/_scripts/MakeFriendsLivingLetter.cs:329)
Antura.Minigames.MakeFriends.<EndRound_Coroutine>c__Iterator3:MoveNext() (at Assets/_games/MakeFriends/_scripts/MakeFriendsGame.cs:418)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Antura.Minigames.MakeFriends.MakeFriendsGame:EndRound(Boolean) (at Assets/_games/MakeFriends/_scripts/MakeFriendsGame.cs:388)
Antura.Minigames.MakeFriends.MakeFriendsGame:OnLetterChoiceSelected(LetterChoiceController) (at Assets/_games/MakeFriends/_scripts/Ma

**Comment by FrancyCavallari** [comment]
@StefanoCecere I added you to this issue since it seems related to "shaddah"... if we have time we have a look at it
