### ISSUE TITLE
[MakeFriends] the 2 words should not share a letter is a different form

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#588]
in this case...
![image](https://user-images.githubusercontent.com/17926293/34883340-a8643f64-f7b9-11e7-9244-e7e18db91777.png)
The Left Word has the letter Beh-Medial, while the Right Word has the Beh-Final
Among the answers there is Beh-Medial (last one on the right)...
... and it's the correct answer!
![image](https://user-images.githubusercontent.com/17926293/34883462-f77b937c-f7b9-11e7-8eb1-5e67340f0f87.png)

PS: MakeFriends should also avoid to use words with diphtongs!

**Comment by FrancyCavallari** [comment]
Another example (very evident):
![image](https://user-images.githubusercontent.com/17926293/34883637-6f61a41c-f7ba-11e7-9265-6f922042c66f.png)

**Comment by FrancyCavallari** [comment]
I had the problem also with a letter with diactiric and the other one without it:
![image](https://user-images.githubusercontent.com/17926293/34886348-fcf12b38-f7c2-11e7-9c62-7d21821d21b7.png)

**Comment by CatmanIta** [comment]
Fixed:
- added VisualForm strictness to letters in MakeFriends
- word filters now exclude words with diphtongs
- I could not find an error with diacritics, tho. Maybe it was a visual bug? I'll need a teacher report to catch it

**Comment by FrancyCavallari** [comment]
Better redo the builder (alef_final is happens too often)... I'll test it again with the new builder

**Comment by CatmanIta** [comment]
Redone
