### ISSUE TITLE
[Map] Culling/Flickering problem with the park/grass on Stage 6

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#590]
Go to the Map (LB 6.11-6.12)
Scroll and notice that the park/grass on the bottom left of the screen appears/disappear:
![image](https://user-images.githubusercontent.com/17926293/34893618-5405a65e-f7de-11e7-97c2-a2e7b4b6ce04.png)
![image](https://user-images.githubusercontent.com/17926293/34893598-3347eaa8-f7de-11e7-9550-aadcedc795e4.png)

@StefanoCecere I assigned it to you... because I'm not sure who should fix it

**Comment by FrancyCavallari** [comment]
Much better!
There is only a popping element under the scissors...
![image](https://user-images.githubusercontent.com/17926293/34938140-787fa5c4-f9e7-11e7-98f0-c4424923b285.png)
![image](https://user-images.githubusercontent.com/17926293/34938162-8798faf6-f9e7-11e7-9aec-94cb054e045b.png)

**Comment by StefanoCecere** [comment]
seems fixed now
