### ISSUE TITLE
[Vocabulary] This letter has no sound (phoneme)

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#593]
Playing MakeFriends I noticed that this letter has no sound/phoneme:
![image](https://user-images.githubusercontent.com/17926293/34936028-2c6884b4-f9e0-11e7-936d-acc3a45b086f.png)

**Comment by StefanoCecere** [comment]
ma è ain_kasrah? nel book è così! (and it has sound)
<img width="99" alt="screen shot 2018-01-17 at 17 50 53" src="https://user-images.githubusercontent.com/640536/35055345-4b21c4f8-fbaf-11e7-8d42-0ed8f536aab1.png">

**Comment by FrancyCavallari** [comment]
No, I think it's "hamza_kasrah"!
And in LetterData has "alef_kasrah" in the PhonemeSound field... so it should work now... to be tested!
PS: not sure it is present in the book...

**Comment by StefanoCecere** [comment]
that's the point.. it's not in the book since it's jsut a symbol and now wedon't show symbols in the book... uhm,...

**Comment by FrancyCavallari** [comment]
maybe we could add Symbols and Special Letters (Lam_Alef) after the 28 basic letters...

**Comment by StefanoCecere** [comment]
now hamza_kasrah sounds well
