### ISSUE TITLE
[Map] the finger animation should be on top of everything else...

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#602]
![image](https://user-images.githubusercontent.com/17926293/34978333-2eea3606-fa9e-11e7-953a-a1dec66a4b0c.png)

**Comment by Demigiant** [comment]
This was an initial design choice and not fixable. The tutorialUI finger was made as part of the world, so it could be used to draw race lines in some games (:P). The solution would be to pass it an overlay camera (via TutorialUI.SetCamera), but it would complicatre things for the map positioning I guess.

**Comment by FrancyCavallari** [comment]
Will not fix!
