### ISSUE TITLE
[Assessment_CompleteWord_Form] it should accept also the diacritics

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#603]

**Comment by CatmanIta** [comment]
![image](https://user-images.githubusercontent.com/3244662/35110659-a32d2168-fc79-11e7-822b-8c4042a0bea2.png)

Added in [588e6be]

**Comment by CatmanIta** [comment]
Actually, the Assessment doesn't handle the case correctly. Trying to fix it!
