### ISSUE TITLE
[Map] The map is a mess on device!

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#606]
both on Android and iOS
![image](https://user-images.githubusercontent.com/17926293/34992362-46a22040-facd-11e7-857d-5229bf34506b.png)

**Comment by FrancyCavallari** [comment]
It does not happen in the Editor

**Comment by CatmanIta** [comment]
Problem happens also in the Windows build.
It was a sorting problem using editor-only variables.
Fixed in [0e33bae]
