### ISSUE TITLE
[Games_Counting] the 2 Counting games are not coherent

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#609]
Q: The 2 Counting games (FastCrowd_Counting and Balloons_Counting) behave differently... one starts from 1 the other one form 0... is it ok?
A: If you play them in stage 4, yes, the 0 can't appear because it requires a letter that is learned in stage 5. The game picks only numbers they can cover.
Q: they both appear in PS 4.15.1... it must be a mistake if "0" should not appear earlier than stage 5!
A: When we designed the curriculum, we specified that they should appear after stage 4. If it's used for the last LB of stage 4, it can be done without the 0.
Q: so both games could start with 1 in Stage 4 and both games could start with 0 in stage 5... I don't see why only one game should start from 0 in stage 5...
A. Let me check...

**Comment by FrancyCavallari** [comment]
Added @CatmanIta because I will need his advice about how to fix/change the 2 Counting games (once we will have defined exaclty what we want with Safaa)

**Comment by FrancyCavallari** [comment]
So the final decision is the following:
- Counting games only from stage 6 (but we still introduce the numbers (words) along the way so we don't hit them with all the numbers at once)
- Both games should start counting from 0

**Comment by CatmanIta** [comment]
FastCrowd now counts from zero [f962b0b]
