### ISSUE TITLE
[Arabic] how should we manage "lam_alef" in LetterInWord and BuildWord games? 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#611]
Since it's the combination of 2 letters it may create confusion for the kids... like in this case:
![image](https://user-images.githubusercontent.com/17926293/34999026-df0a48f4-fae0-11e7-8982-22cbedb18e40.png)

**Comment by FrancyCavallari** [comment]
splitter will not split the "lam_alef" in 2 letters... so it should work for both LetterInWord and BuildLetter games... to be tested!

**Comment by CatmanIta** [comment]
Lam Alef is now always treated as a single letter, regardless of the game.

**Comment by CatmanIta** [comment]
FIxed in [975b3d8]
