### ISSUE TITLE
[Subtitles] Subtitles should be disable by default... 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#614]
... but they can be turned ON in the Options (the Subtitles icon is already present in the Options, even if not working yet)
![image](https://user-images.githubusercontent.com/17926293/35031777-b1d3b332-fb64-11e7-9476-7b73149a1e32.png)

**Comment by StefanoCecere** [comment]
fixed by 6673c5110ef7dbb9b4263b14e72eac393977ac99

**Comment by FrancyCavallari** [comment]
I installed the new version on Android and started the game... the Option is now working well but Subtitiles are ON at the beginning.
