### ISSUE TITLE
[Arabic] Beh letter is missing Name Sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#616]
Log:
> LetterData(): Requested Name Sound is missing beh
> Warning: cannot find audio clip for letter:(ب) beh filename:

NOTE: I got this error in PS 1.1.100 (and all the other letters are ok)
![image](https://user-images.githubusercontent.com/17926293/35032991-5074e2fa-fb69-11e7-85d6-f6e5cfa6ca86.png)

**Comment by StefanoCecere** [comment]
fixed by 658969e03cb8ee1d2aa91e89440cb75f23ad6fae
