### ISSUE TITLE
[Boot] The splashscreen during the loading is wrongly animated

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#623]
it happens only on Device (both Android and iOS).
If we don't have time to produce a nice animation better leave the static screen.

**Comment by FrancyCavallari** [comment]
Much better!
The only possible issue now is that after the 2 zoom-in splashscreens the screen goes to black... and loading could be long on some device (on my android the black screen stays for 5 seconds).
Ideally it would be prefect to have the second splashscreen staying on screen until the loading is completed.... anyway I mark it low-priority since the current solution is acceptable!

**Comment by StefanoCecere** [comment]
i changed the first scene with a smaller bootstrap scene.. maybe it's  better now
