### ISSUE TITLE
[FirstContact] Tutorial Finger animation is visible on Stage 3

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#634]
Create a Profile and reach the map for the first time (PS 1.1.1): the finger animation explain to touch Antura over PS 1.1.1.
If you press the Stage 3 button you can see that the finger animation is visible (pretty big) over the Stage 3.
![image](https://user-images.githubusercontent.com/17926293/35085915-df00a362-fc2a-11e7-88e6-876e57cea26f.png)
![image](https://user-images.githubusercontent.com/17926293/35085753-57d403ac-fc2a-11e7-8f4c-3418e71364b2.png)
![image](https://user-images.githubusercontent.com/17926293/35085823-930091fc-fc2a-11e7-96d1-7cdb538f124f.png)

**Comment by CatmanIta** [comment]
Fixed in [a49f734]
