### ISSUE TITLE
[Audio] Missing female audio file

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#635]
Female audio file expected for localization for

- [x] ID Assessment_Select_Letter_Listen was not found (in PS 1.1.100)
- [ ] ID MakeFriends_letterinword_Tuto
- [x] Profile_Avatar
- [x] Profile_Color
- [x] Action_PressPlay
- [x] Profile_Age
- [x] SelectGame_Tuto_2
- [x] AnturaSpace_Tuto_Cookie_1
- [x] AnturaSpace_Tuto_Cookie_2
- [x] UI_AreYouSure

**Comment by StefanoCecere** [comment]
there is no Assessment_Select_Letter_Listen_F.waf file
@HamzaChioua up to you!

**Comment by FrancyCavallari** [comment]
It seems we are missng many/most/all of Ibtissam dialogs in Female form

**Comment by StefanoCecere** [comment]
@HamzaChioua this is mostly for you!
