### ISSUE TITLE
[Map] The animation of unlock next PS is too slow

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#636]
The animation of the little Dots and the next PS marker (pin or pencil) appearing is too slow and it could be nicer (now it's "robotic/cold").

**Comment by CatmanIta** [comment]
Avoid clicking during this part.

**Comment by CatmanIta** [comment]
Added better animation timings (as intended! they were too fast)

**Comment by FrancyCavallari** [comment]
Can we speed up the appearence of the little Dots?
They are still too slow... we need this animation to be quick and eye-catching...

**Comment by CatmanIta** [comment]
Fixed in [e843343]
