### ISSUE TITLE
[MakeFriends] the end game sequence is very silent, no SFX

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#639]
@HamzaChioua can you please suggest what SFX to use during the end game animation (before the End Game screen appears)? Maybe we could have Antura barking...
![image](https://user-images.githubusercontent.com/17926293/35092810-d2e1e7ec-fc40-11e7-9301-aaf37a8537ba.png)

**Comment by HamzaChioua** [comment]
Yes, Antura barking fits well 
(Sfx.DogBarking)
