### ISSUE TITLE
[Map] wrong behavior when starting a play session before Antura reaches the corresponding Dot

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#643]
Enter the Map
Select a PS away from Antura (from the current PS)
While Antura moves there touch again to start the play session
Notice that something stange/wrong happens!

Here I started an Assessment (1.7.100) but Antura was still over a PS and I get the Game Selector (that is not present for assesments)
![image](https://user-images.githubusercontent.com/17926293/35106526-b8d9a582-fc6e-11e7-9ea0-df8b1de1f89f.png)

**Comment by CatmanIta** [comment]
Fixed in [0e69b7a]
