### ISSUE TITLE
[Audio] teh_marbuta is missing Phoneme Sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#645]
LetterData(): Requested Phone Sound is missing teh_marbuta

Safaa wrote:

> teh_marbuta is a trick from the beginning as it is not a real letter, just a sound "a" indicating the female version of a word. What I suggest is:
> - either using it as a letter and the phonem will always be just "a" (same as alef_fathah)
> - not using it as a letter since we decided to only cover the basic arabic alphabet for a start, this way, it will never be picked in the mini-games

@StefanoCecere can you please confirm the first option is the simplest one? If so we should add "alef_fathah" as PhonemeSound of "teh_marbuta" in LetterData table!

**Comment by StefanoCecere** [comment]
done 437b700218b6dbb5c48ae86ce1fa1687a353a1fd
