### ISSUE TITLE
[HideAndSeek] A Warning appear in the Log

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#646]
Animator is not playing an AnimatorController
UnityEngine.Animator:SetBool(String, Boolean)
Antura.LivingLetters.LivingLetterController:OnStateChanged(LLAnimationStates, LLAnimationStates) (at Assets/_app/_scripts/LivingLetter/LivingLetterController.cs:215)
Antura.LivingLetters.LivingLetterController:set_State(LLAnimationStates) (at Assets/_app/_scripts/LivingLetter/LivingLetterController.cs:135)
Antura.LivingLetters.LivingLetterController:SetState(LLAnimationStates) (at Assets/_app/_scripts/LivingLetter/LivingLetterController.cs:331)
Antura.Minigames.HideAndSeek.<MoveTo>c__AnonStorey0:<>m__0() (at Assets/_games/HideAndSeek/_scripts/HideAndSeekLetterController.cs:67)
DG.Tweening.Tween:OnTweenCallback(TweenCallback) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:276)
DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:260)
DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:436)
DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)

**Comment by davidebarbieri** [comment]
The warning started from a certain Unity version and it is harmless. I'd leave the warning,
removing calls when the gameobject is not active is too much bug-prone at this stage.
