### ISSUE TITLE
[Profile] texts are difficult to read

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#647]
On my Android phone I see it like this:
![image](https://user-images.githubusercontent.com/17926293/35111133-d44d6018-fc7a-11e7-8b79-a7b97fbd51b1.png)
On PC I can read the numbers but in the phone itself is not very comfortable...
... better if:
1. we increase the size of the font (we could also increase the size of the bars and the icons)
2. we find a better (Arabic?) format to express Days/Hours/Minutes...

**Comment by StefanoCecere** [comment]
ahh i was reworkign the Ui like this.. i guess much better.. note the PlayerIcon is this the correct one? @Demigiant can you check the Plyaericon also here in the PlyerProfile?

<img width="1019" alt="screen shot 2018-01-19 at 11 13 41" src="https://user-images.githubusercontent.com/640536/35145956-e42596e2-fd09-11e7-85b8-eb84409f66e0.png">

**Comment by FrancyCavallari** [comment]
Just one note: if we go for a Right-to_left layout the Avatar should be on the right!
PS: to me the avatar looks like the old one with Japan-rays instead if the new "yellow gears"
