### ISSUE TITLE
[Arabic] Error about "lam_alef" in Assessment_MatchLettersToWord

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#649]
Cannot find a single character for lam_alef + kasrah. Diacritic removed in (اﻻِﺛْﻨَﻴﻦ).
UnityEngine.Debug:LogError(Object)
Antura.Helpers.ArabicAlphabetHelper:AnalyzeArabicString(DatabaseObject, String, Boolean, Boolean) (at Assets/_app/_scripts/Language/ArabicAlphabetHelper.cs:263)
Antura.Helpers.ArabicAlphabetHelper:SplitWord(DatabaseObject, WordData, Boolean, Boolean) (at Assets/_app/_scripts/Language/ArabicAlphabetHelper.cs:148)
Antura.Database.VocabularyHelper:GetLettersInWord(WordData) (at Assets/_app/_scripts/Language/VocabularyHelper.cs:299)
Antura.Database.VocabularyHelper:WordContainsAnyLetter(WordData, IEnumerable`1, LetterEqualityStrictness) (at Assets/_app/_scripts/Language/VocabularyHelper.cs:599)
Antura.Teacher.LettersInWordQuestionBuilder:FindEligibleWords(Int32) (at Assets/_app/_scripts/TeacherAI/QuestionBuilding/QuestionBuilders/LettersInWordQuestionBuilder.cs:165)
Antura.Teacher.<CreateSingleQuestionPackData>c__AnonStorey0:<>m__0() (at Assets/_app/_scripts/TeacherAI/QuestionBuilding/QuestionBuilders/LettersInWordQuestionBuilder.cs:95)
Antura.Teacher.VocabularySelectionAI:SelectData(Func`1, SelectionParameters, Boolean, Boolean) (at Assets/_app/_scripts/TeacherAI/AIEngines/VocabularySelectionAI.cs:200)
Antura.Teacher.LettersInWordQuestionBuilder:CreateSingleQuestionPackData(Int32) (at Assets/_app/_scripts/TeacherAI/QuestionBuilding/QuestionBuilders/LettersInWordQuestionBuilder.cs:94)

**Comment by StefanoCecere** [comment]
check now please
