### ISSUE TITLE
[UI] the UI does not "block" the interaction with 3d elements below on Android

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#651]
On Andoird if you touch a UI element (i.e. the X button in map) you also select the 3d elements below it (i.e. a Pin).
It can be annoying because pressing X in the Map will make Antura step back and if you select again your profile you are no more on the most advanced PS (to progress in your journey)

Another case is in the Profile screen, pressing X you close the panel AND you select the pin below it (so Antura moves there)

NOTES: 
- it happens alo in the minigames (i.e. EndGame screen) but it's less annoying
- It does not happen on PC/Editor.

**Comment by StefanoCecere** [comment]
@Demigiant and @CatmanIta with d84f49b91f1a28ace9445d05e709777f9145e8a1 i introduced a "click blocker" for raycasts (used in the modal window of the book)

yes PC has different behavior than mobile in the clicks

**Comment by StefanoCecere** [comment]
could be fixed by b4e7d10e279eefae118b61b8147f0284625f461b

**Comment by FrancyCavallari** [comment]
the collision zone for PLAY/CONTINUE has been reduced and it should not overlap anymore with Antura Space and X buttons... but the issue is still open a general one.
One specific example of the issue is this one: #531
