### ISSUE TITLE
[Audio] Missing Letter sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#653]
LetterData(): Requested Name Sound is missing lam_alef_maddah

**Comment by HamzaChioua** [comment]
@FrancyCavallari  which type of file is needed here? "name" or "sound" ? 
Thx

**Comment by FrancyCavallari** [comment]
Name! @HamzaChioua

**Comment by HamzaChioua** [comment]
ok. Here is it 
[lam_alef_maddah.wav.zip](https://github.com/vgwb/Antura_arabic/files/1649720/lam_alef_maddah.wav.zip)
