### ISSUE TITLE
[Reserved Area] a wrong popup is displayed accessing the Install Instruction on Android

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#655]
The PDF opens correctly...
... but when I quit it I get this one:

![image](https://user-images.githubusercontent.com/17926293/35149499-99bbc4c0-fd16-11e7-8997-fec3d33016b8.png)

NOTE: I tried again and I got the popup OK (only in English)
![image](https://user-images.githubusercontent.com/17926293/35149614-19571162-fd17-11e7-9a13-c7f80293b498.png)

**Comment by FrancyCavallari** [comment]
The popup is ok now!
But the flow is still a bit strange on Android compared to PC.

On PC you press the button, the popup opens and when you confirm the PDF opens.
On Android the PDF opens as soon as you press the button... and whe n you come back you find the pupop message.

**Comment by StefanoCecere** [comment]
si, perchè apre il pdf direttamente.. se non lo trova serve il messaggio ma non possiam oasapere a priori se lo apre o meno (se app pdf viewer installata o no!)

**Comment by FrancyCavallari** [comment]
E non possiamo aspettare a che il giocatore clicchi sul Popup per aprire il PDF?
Prima ti avvisiamo che apriremo il PDF e ti diciamo cosa fare se non si apre...
... e poi apriamo il PDF, così il giocatore sa cosa aspettarsi.
