### ISSUE TITLE
[UI] Finger trail not initialized on Android

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#658]
When a tutorial animation starts the finger trail starts from a random position.
On Android only: on PC/Editor it's ok.

**Comment by FrancyCavallari** [comment]
We should check how the Tutorial animation are called...
@CatmanIta can you please check the First Contact?
@davidebarbieri I'll try to write a list of the games in which the problem is present

**Comment by davidebarbieri** [comment]
I saw this on PC/Editor too
