### ISSUE TITLE
[DancingDots] The UI elements are too small (difficult to read)

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#660]
Better make the floating buttons bigger... and maybe also increase the size of the diacritics inside them!
![image](https://user-images.githubusercontent.com/17926293/35152092-37c6b2ba-fd21-11e7-8736-9ea0831bcd3d.png)

**Comment by FrancyCavallari** [comment]
Button Size is ok... but the diacritics inside are still pretty small, can we scale the diacritic up?
![image](https://user-images.githubusercontent.com/17926293/35200451-f7b77c8c-ff0e-11e7-9103-300e7a91e85b.png)

**Comment by davidebarbieri** [comment]
Diacritics were scaled alongwith button; now are even larger
