### ISSUE TITLE
[Arabic] Missing shaddah in the beginning of words

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_arabic#662]
![sc_1](https://user-images.githubusercontent.com/18099842/35176762-f55d27c2-fd72-11e7-8f63-7700c896cf19.png)

The system seems not to know how to handle "al shamsia" and "al qamaria" in the beginning of the words. 
There's a "sukun" on top of the "lam", and the "shaddah" on the following letter is absent (BAD).
This is not specific to the MG in the screenshot, found the issue on several areas of the game.

**Comment by FrancyCavallari** [comment]
linked with #710
