### ISSUE TITLE
[UI] active LLs during tutorials distract from the flow

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_arabic#665]
It's possible for the player to spam the screen during tutorials triggering a lot of audio, and lose focus on what has to be done.
Maybe we should try to disable interactions until tutorials are over.

**Comment by FrancyCavallari** [comment]
@HamzaChioua do you mean the mingames tutorial, correct?

**Comment by HamzaChioua** [comment]
@FrancyCavallari Yes

**Comment by davidebarbieri** [comment]
Can't just disable interactions during tutorial since tutorials need interaction, and they are managed differently in each minigame; need some design decisions and programming for each minigame - too complex to do it now
