### ISSUE TITLE
[Assessment][Audio] Audio triggered on scene loading, before tutorial 

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_arabic#666]
the audio of letter or word to guess is played once on loading, before the tutorial .

**Comment by FrancyCavallari** [comment]
The current flow of the Asssessments is:
- Loading
- sound of the correct answer 
- voive tutorial
- spawn of the possible answers 
- sound of the correct answer

We may want to change it in the future...

**Comment by FrancyCavallari** [comment]
We won't change it... it's ok and coherent with the animations to play the sound of the correct answer when it appears and then repeat it when you have to answer.
