### ISSUE TITLE
[AnturaSpace][UI] SFX missing in some buttons in Antura space 

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_arabic#668]
Some buttons are not playing the generic button SFX when pressed : 
- "Close button" from Antura customisation sub menu
- Lower menu : BG customisation buttons
- photo submit/cancel buttons

![sc_4](https://user-images.githubusercontent.com/18099842/35183835-4e45a550-fde4-11e7-8317-eb60e5e7abf1.png)
![sc_5](https://user-images.githubusercontent.com/18099842/35183836-4e7b75cc-fde4-11e7-9792-21c4038fc987.png)
![sc_7](https://user-images.githubusercontent.com/18099842/35184076-9ec5fed6-fde8-11e7-8206-252a5d55caa0.png)

**Comment by CatmanIta** [comment]
Fixed.
