### ISSUE TITLE
[AnturaSpace][UI] BG customisation menu SFX 

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_arabic#669]
in the background customisation menu, the sound of disabled (RED) buttons is played repeatedly if the player tries to drag an item not available.

The SFX  should play only once.

![sc_6](https://user-images.githubusercontent.com/18099842/35183904-4424d89c-fde5-11e7-89a8-215a2a7a38a9.png)

**Comment by FrancyCavallari** [comment]
duplicate than #524 but I keep it open since here it's well explained

**Comment by CatmanIta** [comment]
FIxed

**Comment by CatmanIta** [comment]
I also made sure that the error is played only if dragging up, and not left/right.
