### ISSUE TITLE
[FirstContact] The Tutorial Animation about how to move a decor is not clear

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#675]
Shop tutorial, hot to move an objets from a slot to another.  
The guiding arrow is confusing.  Better to have the starting point on the middle of the object (tree), not on the ground position of it. This way we should also avoid the risk of Antura blocking the interaction with presence.
And the end position could be slightly over the slot, instead of being on the ground.

![image](https://user-images.githubusercontent.com/17926293/35197492-249e63fc-fee0-11e7-989a-7ecbd2e5902d.png)

**Comment by CatmanIta** [comment]
Fixed
