### ISSUE TITLE
[Map] the circle FX under Antura is not active you manually select a PS

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#676]
Enter the Map, and notice there's no circle FX under Antura (and there's no finger animation over it)...
![image](https://user-images.githubusercontent.com/17926293/35274610-ff57e6be-003c-11e8-9307-cbb29925afd4.png)

... then select another PS and notice the the circle FX is now active.
![image](https://user-images.githubusercontent.com/17926293/35274648-21583a7a-003d-11e8-8ab5-d82dc8022e6d.png)

**Comment by CatmanIta** [comment]
Fixed
