### ISSUE TITLE
[FastCrowd_buildword] Stuck at PS.1.10.2

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#677]
PS 1.10.2, it stops working at the beginnng of the second word:
![image](https://user-images.githubusercontent.com/17926293/35319972-60fa026c-00e2-11e8-855a-84fcea1c1059.png)

The Console Log does not show any error/mistake... the pause menu is working OK and the Teacher report seems OK too.

NOTE: the issue does not depend on the PS... FastCrowd_BuildWord get stuck always at the start of the second round.

**Comment by CatmanIta** [comment]
The issue is with the WidgetPopUp's button and the new OneShot functionality.

When the PopUp appears at the first round, the button works.
At the second round, the button does not reset and cannot be clicked anymore.
I see that the [GlobalUI] has that button as OneShot by default.

**Comment by FrancyCavallari** [comment]
Fixed by removing the OneShot from this specific button!

**Comment by zixofranic** [comment]
The issue still exists, in the same game on Android. Nevertheless, the tester was able to proceed playing by pressing to the right of the button. And this is happening when the image is shown before the game but the button is working well on the feedback after the round is finished. 

![1_10-same-error-but-can-be-bypassed-by-pressing-next-to-the-btn](https://user-images.githubusercontent.com/8046715/35795894-68c5e3be-0a63-11e8-9cb7-0430825439bf.png)

**Comment by zixofranic** [comment]
> game

ound

**Comment by zixofranic** [comment]
The issue still exists, in the same game on Android. Nevertheless, the tester was able to proceed playing by pressing to the right of the button. And this is happening when the image is shown before the round but the button is working well on the feedback after the round is finished. 

![1_10-same-error-but-can-be-bypassed-by-pressing-next-to-the-btn](https://user-images.githubusercontent.com/8046715/35795894-68c5e3be-0a63-11e8-9cb7-0430825439bf.png)

**Comment by FrancyCavallari** [comment]
here's something wrong with this button...
.. it seems to have 2 parts testing on PC/Editor:
1. if I click on the button itself is works well
2. if I click on the Red circle the PLAY icon change state (see screenshot below) and the game continues
![image](https://user-images.githubusercontent.com/17926293/35805338-afa496fa-0a7b-11e8-9290-ff65667aadcc.png)

**Comment by FrancyCavallari** [comment]
PS: 
- it happens the same on the left of the PLAY button (not only on the right)
- on iOS and on PC/Editor the button seem to work fine

**Comment by FrancyCavallari** [comment]
On my phone, Android version the PLAY button is working fine... 
... so maybe the problems come from the 2 "parts" of the button that overlaps and behave differently according to the phone...

**Comment by CatmanIta** [comment]
Removed the overlap.
