### ISSUE TITLE
[Audio] Letter yeh_hamza has no Sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#678]
`LetterData(): Requested Phone Sound is missing yeh_hamza`

**Comment by zixofranic** [comment]
reported as well in egg game. No sound for hamza

**Comment by StefanoCecere** [comment]
we dont' have phoneme sound for  yeh_hamza
i'm waiting for confirm that we can use the alef phoneme sound

**Comment by HamzaChioua** [comment]
We discussed this case last saturday in #antura_pedagogy channel.
In my opinion, it should play the "alef" sound.

**Comment by FrancyCavallari** [comment]
Here you have a screenshot of the letter with no sound...

![image](https://user-images.githubusercontent.com/17926293/35851115-3d8a261e-0b27-11e8-9a12-2752c2838349.png)

**Comment by StefanoCecere** [comment]
yeh_hamza has been disabled, so i think we can close this issue
