### ISSUE TITLE
[UI] Play button stops working if clicking after pause.

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#681]
The Play button stops working after you do the following during a game:
- click Pause
- immediatly click the Play button
- since animation has not finished, the Play button does not remove the pause state
- Play button is one shot, remains clicked
- The Play button won't work anymore

**Comment by Demigiant** [comment]
That's how a one-shot button should correctly work. If there's the need of managing the button differently then I'd say to simply disable the one-shot

**Comment by CatmanIta** [comment]
Either that, or the one-shot should not be clickable while the panel is appearing, since there is a discrepancy between the one-shot behaviour (not triggered) and animation (played)

**Comment by FrancyCavallari** [comment]
Fixed removing the OneShot flag from the PLAY button in the pause menu
