### ISSUE TITLE
[Missing Letter] 2 words spelled wrong in the database

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#683]
### In missing letter game 2 words are spelled wrong and resulting in choosing the wrong letter for the senario. the vegetarian and vegetarians.. attached is database fixes (the one on the right are the right ones) and a screenshot from missing letter. 
![missingletter](https://user-images.githubusercontent.com/8046715/35325442-723f487e-00fc-11e8-97e1-c75cc21a37f4.png)
![screenshot_2018-01-24-11-34-48](https://user-images.githubusercontent.com/8046715/35325540-b8eb9598-00fc-11e8-9fd5-7875a82dc07f.png)

**Comment by zixofranic** [comment]
The 2 wrong word for vegetarian and vegetarians are still wrong 
@FrancyCavallari

**Comment by FrancyCavallari** [comment]
@safaarbk maybe the problem is due to the fact that both words include Alef, but Alef is not present in Stage 1... so the words should not appear in Stage 1!!!!
Can you please check and fix the PlaySessionDB?

**Comment by safaarbk** [comment]
Corrected in the PlaySessionDB, thanks for the note

**Comment by FrancyCavallari** [comment]
@safaarbk I checked the PlaySessionDB... now the 2 words are introduced in LB 2.5 ...
... but both words have "alef" that is not introduced until Stage 3.
Is it a mistake???

**Comment by safaarbk** [comment]
Fixed, my mistake
