### ISSUE TITLE
[Assessment] wrong sound for the tah (ة)

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#684]

**Comment by FrancyCavallari** [comment]
In the Pedagogy channel, Safaa explained:

> teh_marbuta is a trick from the beginning as it is not a real letter, just a sound "a" indicating the female version of a word. What I suggest is:
> - either using it as a letter and the phonem will always be just "a" (same as alef_fathah)
> - not using it as a letter since we decided to only cover the basic arabic alphabet for a start, this way, it will never be picked in the mini-games

and since the simplest solution was the first one we implented it this way: so in Phoneme games it sounds like "alef_fathah".

@zixofranic: Do you really see it as an issue?

**Comment by zixofranic** [comment]
This bug was reported by the latest test, and yes it is an issue as the sound of the letter is T and cannot be pronounced as an A.. This was reported in the Egg game and hidden letter 1-6 

So skipping it could be a possibility

![wrongsound it is saying a 1-6- egg and hidden letter](https://user-images.githubusercontent.com/8046715/35795034-876b7de0-0a60-11e8-8703-f2a5b6e2e471.png)

**Comment by FrancyCavallari** [comment]
I asked Safaa in Slack...

**Comment by FrancyCavallari** [comment]
it's ok!
