### ISSUE TITLE
[Assessment] Wrong word in Database

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#686]
### Assessment 1.8
![error](https://user-images.githubusercontent.com/8046715/35327648-d6b83666-0102-11e8-96b8-f57ae566556a.png)

**Comment by safaarbk** [comment]
Confirmed

**Comment by FrancyCavallari** [comment]
OK good, @StefanoCecere you shoudl simply re-import the Vocabulary DB

**Comment by FrancyCavallari** [comment]
In fact it has been already re-imported and it appears correct in the game now:
![image](https://user-images.githubusercontent.com/17926293/35909306-70314076-0bf3-11e8-92f1-907c3e1973c3.png)

So I close the issue!
