### ISSUE TITLE
[Profile] UI Improvements and clarity

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#687]
![image](https://user-images.githubusercontent.com/17926293/35332537-89f69d3c-010b-11e8-8d34-ba7ea9bd0c2d.png)

Few UI improvements:
- [ ] the total Gift number (743) is not "correct"... according the current UX the player can get only 95 Big Rewards (the ones with the Gift Box opening). In fact the "small rewards" (Item color variations) are now always available for all items). So better show 95 as max number of gifts.

- [x] the 3 buttons at the bottom should be rounded/circles... squared elements are always draggable (not buttons) in the UI of the game

- [x] the Avatar is not showing the yellow highlight around it

- [x] the progression/reached-LB-number is missing

**Comment by FrancyCavallari** [comment]
The reward number is still wrong (even if the MAX reward number is now correct = 95):
![image](https://user-images.githubusercontent.com/17926293/35913287-6fcd22f6-0bff-11e8-9aad-07ab45f1a6c0.png)

**Comment by StefanoCecere** [comment]
so please refer this issue to @CatmanIta becasue there is no api to get the "big awards" number

**Comment by FrancyCavallari** [comment]
Also the Number of Star is "strange/wrong": the Demo Profile has all 3 stars so it should have 270/270... but it's not the case.
I also checked another Profile and the Number of Stars displayed here does not match the number of visible stars in the Map.

**Comment by StefanoCecere** [comment]
@CatmanIta we need you for 1)

**Comment by CatmanIta** [comment]
See Antura_FSM channel for the answer I wrote

**Comment by FrancyCavallari** [comment]
The star number is definitely wrong.

I created a new profile and completed the first LB with 3 stars.
![image](https://user-images.githubusercontent.com/17926293/36068308-9d8922d2-0ed2-11e8-8592-cfa410383b86.png)

if I enter the Profile I get this (9 stars):
![image](https://user-images.githubusercontent.com/17926293/36068314-bc728efe-0ed2-11e8-8a23-57740a0ffcd9.png)

I complete PS 1.2.1 with 3 stars:
![image](https://user-images.githubusercontent.com/17926293/36068326-139b21f0-0ed3-11e8-9924-68cd41e5e7e1.png)

And in the Profile I now have 15 stars:
![image](https://user-images.githubusercontent.com/17926293/36068329-2b2254f6-0ed3-11e8-82b9-ee288d062313.png)

**Comment by FrancyCavallari** [comment]
I found the "rule" of what's happening:
- when you complete a PS the stars are added twice! (I don't know why)
- when you complete a Assessment you get 3 stars (most likely because the asessments use the minigame framewrk and they must set a number of stars during the endgame sequence)
