### ISSUE TITLE
[MissingLetter_letterinword] it's too difficult to reach 3 stars

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#695]
In order to reach 3 stars you cannot do any single mistake ... and you have also a time limit!
We should allow at least 1 mistake without losing the possibility to reach 3 stars.
I.e. we could add 1 extra round without changing the limits to reach 1, 2 and 3 stars.

**Comment by CatmanIta** [comment]
Added 2 more rounds and changed limits so they are not based on the total number of rounds (still 3,6,9 answers to win the stars)

**Comment by CatmanIta** [comment]
in [43573c7]
