### ISSUE TITLE
[Arabic] "Vegetarian" and "Vegetarians" have wrong images

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#696]
Both words are Male Nouns... so the drawings should represent 1 and 2 Boys (instead fo girl)
![image](https://user-images.githubusercontent.com/17926293/35434541-d4a42fb6-0287-11e8-8df9-cbbc3f2df79a.png)
![image](https://user-images.githubusercontent.com/17926293/35434559-e0abf4f6-0287-11e8-8119-3d558f860d72.png)

**Comment by FrancyCavallari** [comment]
Pierre delivered the updated images with 1 and 3 boys (instead fo girls)... 
... @StefanoCecere I guess we just need to integrate them into the game.

**Comment by StefanoCecere** [comment]
fixed 4fe4f7fe9548b10f16870fd907d4f1a3a04f487f
