### ISSUE TITLE
[Boot] The new version popup and permission for data collection dialog overlap with the Title and First Contact

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#698]
Install a new version and start the game...
... the "new version popup" opens over the Title Screen and then the Dialog to ask the player permission for anonyous data collection opens as well.
![image](https://user-images.githubusercontent.com/17926293/35524655-78a01e6c-0522-11e8-88ea-fae6df8ec9ee.png)
![image](https://user-images.githubusercontent.com/17926293/35524677-8d2f772e-0522-11e8-8d65-cd3176856fb6.png)
NOTE: depending on the platform you may also have asystem popup asking permission to access the Storage (for the photos).

But the Title Screen starts playing normally:
- the kids voice chants the Title "Antura al wuruf"
- the First Contact welcome dialog plays (girls inviting you to press [+] to create a profile

Better delay the Title Screen normal flow (chant of the Title + First Contact) until the boot popups/dialogs have been completed.

**Comment by StefanoCecere** [comment]
it has been separated in a custom bootstrap scene (that loads before everything else at startup)

**Comment by FrancyCavallari** [comment]
In the last version I had no popup after installing it... so I cannot test...
