### ISSUE TITLE
[Map] The first time you enter with the Demo Profile you see Antura on 1.1.1 before scrolling to stage 6

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#699]
1. Delete all profiles using the debug menu
2. Go to the reserved Area aand create the Demo profle
3. Start the game with the Demo Profile
4. pass Mood and Daily Reward
5. when you reach the Map you notice that Antura and the camera are on PS 1.1.1...
![image](https://user-images.githubusercontent.com/17926293/35524979-74cf6dbe-0523-11e8-9e67-b4a828e804a5.png)
... but soon the camera start scrolling towards the Stage 6...
![image](https://user-images.githubusercontent.com/17926293/35525021-948d2f38-0523-11e8-9427-0eade8092a4a.png)
... and also Antura moves to the last PS...
![image](https://user-images.githubusercontent.com/17926293/35525068-bcc15646-0523-11e8-8c1a-0269caefa324.png)
... until both reaches PS 6.15.100
![image](https://user-images.githubusercontent.com/17926293/35525118-dd85e298-0523-11e8-8292-be5c1637af07.png)

This happens only the very first time you load the Demo Profile... all the other times Antura and the camera are immediately on PS 6.15.100, like it should be.

**Comment by FrancyCavallari** [comment]
On Android the problem seems bigger:
the first time you enter the map (right after creating the Demo Profile) Antura stays on PS 1.1.1 and the Stage buttons do not work!

**Comment by CatmanIta** [comment]
Fixed in [19bdaae]

**Comment by FrancyCavallari** [comment]
Fixed on PC/Editor... I wait to test on Android before Closing it
