### ISSUE TITLE
[Maze] The rocket entrance animation at every round is too long 

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#701]
It could be ok for the first round but having the rocket flying in circle at EVERY ROUND while the player waits to play is annoying...
![image](https://user-images.githubusercontent.com/17926293/35749712-c1626aaa-0852-11e8-9129-8958d31804c0.png)

Better have a much simpler/shorter entrance animation between rounds!

**Comment by CatmanIta** [comment]
After the first tutorial round, the animation is different and faster (from above). [b7136b2]
