### ISSUE TITLE
[Arabic error] An image is associated to a wrong word 

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#702]
### The current image in fast crowd is associated to a wrong word. Apparently it should say my daughter (بنتي) but instead it is associated to Bin like coffee (بن). It could be wrong in the database or the image is wrong... 

![wrong word for this image bin](https://user-images.githubusercontent.com/8046715/35795346-8cc0c31c-0a61-11e8-8f94-5cba6e98d92c.png)

**Comment by FrancyCavallari** [comment]
My_daughter has a different image in the vocabulary:
![image](https://user-images.githubusercontent.com/17926293/35802792-cadd5a38-0a71-11e8-8735-6300a922ae0c.png)

This image is "Son":
@zixofranic are you sure the word to find was "My daugther"?

**Comment by zixofranic** [comment]
The word bin is not used in this context. the right word is إبن
the word بن is used in special cases when you call someone like Ziad bin Joseph = Ziad son of Joseph

Let's double check with Safaa

**Comment by FrancyCavallari** [comment]
I asked Safaa in Slack...

**Comment by StefanoCecere** [comment]
i fixed the drawing for "son" word (it wasn't good). if there is something else to change, please re-open this issue
