### ISSUE TITLE
[Assessment] Same letter showing twice

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#703]
### Assessment 1-5, The letter ya is showed twice in an assessment. The tester was not able to test if any of them is considered wrong as his first selection was correct. 

![two ya2 one is right _ 1-5](https://user-images.githubusercontent.com/8046715/35796161-49adaf9c-0a64-11e8-9256-07ba3b710b0d.png)

**Comment by FrancyCavallari** [comment]
@zixofranic : Do you mean that one of the 2 identical letter was the correct answer?

**Comment by zixofranic** [comment]
@FrancyCavallari we couldn't know as the first option we chose was right, so I don't know if the second would have been considered wrong.

**Comment by CatmanIta** [comment]
Here too I think that's a dipthong. Will check

**Comment by FrancyCavallari** [comment]
Agreed, let's remove the diphthongs from all LetterPhoneme and LetterAny games

**Comment by CatmanIta** [comment]
I think this is the LetterAny assessment. If so, fixed with [a9f62db]
