### ISSUE TITLE
[Parent section] Repeated word

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#704]
### repeated word in the parent access page. See attached image. 

![screenshot_2018-02-05-10-43-02](https://user-images.githubusercontent.com/8046715/35797651-ff4625ba-0a68-11e8-8737-d68d753a7809.png)

**Comment by FrancyCavallari** [comment]
@CatmanIta : If I remember well you did a custom system to have the instructions in both English and Arabic... please check the double word.

**Comment by CatmanIta** [comment]
I think this is it, correct?

![image](https://user-images.githubusercontent.com/3244662/35851751-3c3795f6-0b29-11e8-8c6e-e741f33b951d.png)

**Comment by CatmanIta** [comment]
Fixed in [62bbd8e]

**Comment by FrancyCavallari** [comment]
@zixofranic can you please confirm that now it's ok?

**Comment by zixofranic** [comment]
Yes it is right.
