### ISSUE TITLE
[Egg game] 2 right options, but one is considered right

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#706]
### 2.7.2 in the egg game, the tester received 2 yeh letter that are both right but only one is considered right by the game. Please see attached image. 

![screenshot_2018-02-05-12-16-19](https://user-images.githubusercontent.com/8046715/35799695-31c93404-0a6f-11e8-8286-afeb9082089b.png)

**Comment by zixofranic** [comment]
For some reason, it happened with another yeh in another egg game.

**Comment by CatmanIta** [comment]
I suspect that is a dipthong (yeh_diph), which presence or absence I think was left for later choice. I suggest removing them.

**Comment by FrancyCavallari** [comment]
Agreed, let's remove the diphthongs from all LetterPhoneme and LetterAny games

**Comment by CatmanIta** [comment]
Fixed with [a9f62db]
