### ISSUE TITLE
[Mixed letters] letters are not in right format and are considered right

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#707]
### We placed the letter YEH in the right places in the word, but with the wrong format, and it was accepted as right. The first YEH should be in the end of the word and the one used at the end of the word should be in the middle of the word. 

![screenshot_2018-02-05-13-22-30](https://user-images.githubusercontent.com/8046715/35802724-c9b09a46-0a79-11e8-999d-ecda33d71002.png)

**Comment by FrancyCavallari** [comment]
Fixed verified
![image](https://user-images.githubusercontent.com/17926293/35851647-eb876640-0b28-11e8-8b7f-74fbbe85aa01.png)
