### ISSUE TITLE
[PlaySessionDB] MissingLetter_LetterForm is not present in Stage 2, 3 and 4

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#713]
MissingLetter_LetterForm is introduced in PS 1.5.1 ... but then it's not used anymore until PS 5.9.1 and later in PS 6.9.1.
I think it's a mistake because we need to introduce/discover the forms of all the letters, so it should be present in all Stages!
I'd recommend to include MissingLetter_LetterForm in PS:
- 2.5.1
- 3.5.1
- 4.5.1
- 5.5.1
- 6.5.1

and to remove it from PS:
- 5.9.1
- 6.9.1

I'll check with Safaa before making the changes... and re-importing the PlaySessionDB.

**Comment by safaarbk** [comment]
Confirmed. X.5.1 contains currently 2 minigames so we can add it as mini-game #2 and make it 3 mini-games.

**Comment by FrancyCavallari** [comment]
We implemented it as minigame #3 like it was present in PS 1.5.1 ...
... so the sequence of minigames in PS X.5.1 is always:
1. FastCrowd_letterform
2. DancingDots_letterany
3. MissingLetter_letterform

It's a good order because it alternates forms and diactiritics... Safaa confirmed it's ok.
@StefanoCecere you just have to re-import the PlaySessionDB

**Comment by StefanoCecere** [comment]
done
