### ISSUE TITLE
[Arabic] "Yeh_hamza" should be removed

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#715]
it's currently present only in one word: pearl...
![image](https://user-images.githubusercontent.com/17926293/35929062-e6922b6e-0c2e-11e8-873b-e78ef9446b6c.png)

We should spell it differently (with yeh and hamza separated)

**Comment by StefanoCecere** [comment]
yeh hamza has been removed as letter.
pearl word has been disabled in words list and in playsessions

**Comment by StefanoCecere** [comment]
note: we have still 4 words with the yeh_hamza:

[Log] Cannot parse letter ﺋ (FE8B) in اﻟﺬﺋﺐ
[Log] Cannot parse letter ﺋ (FE8B) in اﻟﺮاﺋﻊ
[Log] Cannot parse letter ﺋ (FE8B) in ذِﺋﺐ
[Log] Cannot parse letter ﺋ (FE8B) in رَاﺋﻊ

**Comment by FrancyCavallari** [comment]
I asked Safaa to fix the spelling of the 4 words ...

**Comment by FrancyCavallari** [comment]
... still waiting for Safaa to fix the 4 words.
