### ISSUE TITLE
[ThrowBalls_BuildWord] the highlight of the letter to hit should avoid Shaddah

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#716]
With the new special management of Shaddah diacritic we have to take care of the consequences on the gameplay. 
In ThrowBall_BuildWord a full word is written and a letter is highlighted...
![image](https://user-images.githubusercontent.com/17926293/35965767-343caa46-0cbc-11e8-85d8-9eb71b95006a.png)

... but the highlighted letter may have a "shaddah" while the letter to play with (the letter to hit) will be without "shaddah".

The best solution we could think of is to highlight the letter but to not highlight shaddah... This way it will be coherent gameplay wise. Shaddah would be some sort of extra symbol of the word.
But we are not sure that is easily feasable on the technical side

**Comment by CatmanIta** [comment]
I studied how the highlight here works. I need a word with Shaddah as an example, if I am guessing it right I should be able to separate it, can you provide one? Thanks
