### ISSUE TITLE
add new letters

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#718]
- [x]  lam_alef_hamza_hi
- [x]  lam_alef_hamza_hi_dammah
- [x]  lam_alef_hamza_low
- [x]  lam_kasrah_alef_hamza_hi

for the 3 remaining , they should point to “alef” sounds :
- [x]  hamza_fathah = alef_fathah
- [x]  hamza_kasrah = alef_kasrah
- [x]  hamza_dammah = alef_dammah

andremove
- [x]  waw_hamza
- [x]  yeh_hamza

**Comment by FrancyCavallari** [comment]
I cannot validate it myself... I'll ask Safaa to review it as soon as have a new build

**Comment by FrancyCavallari** [comment]
I closed the issue... we will open a new one if a specific problem is found
