### ISSUE TITLE
[Arabic] "hamza" has no sound

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#723]
![image](https://user-images.githubusercontent.com/17926293/36060636-ccb35760-0e4d-11e8-91e3-61d1210da35f.png)

and the Log tells:

> Warning: cannot find audio clip for letter:(ء) F-Isolated hamza filename:hamzah_fathah

PS: moreover "hamza" is set a symbol in the LetterDB (and it appears among the symbols in the Book)... but we have it as a letter in several words (unlocked in PS 5.1.1)... wouldn't be more logical to have it among the Special Letters in the book?

**Comment by StefanoCecere** [comment]
with 305fa3a6ee1e92e7a40e421db9954ab8834670b9 set to LetterVariation and PhonemeSound to  alef_hamza_hi_fathah

**Comment by FrancyCavallari** [comment]
waiting @HamzaChioua confirmation that it's ok before closing it

**Comment by HamzaChioua** [comment]
In my opinion it should sound like alef_sukun, because it doesn't have diacritic on it .

**Comment by FrancyCavallari** [comment]
... and @HamzaChioua do we have the "alef_sukun" sound in the game?

**Comment by HamzaChioua** [comment]
Yes. We have the audiofile

**Comment by FrancyCavallari** [comment]
Ok I have updated the LetterData.
@StefanoCecere please check the the audiofile is present and reimport the DB
