### ISSUE TITLE
[Teacher] we should avoid the same word (with and without article) to appear in the same round

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#730]
in all games/assessments like MakeFriends in which the player has to look for a shared letter, we should avoid having the same worf to appear twice: with and without article. In fact in that case there are always several common letters and the game becomes less interesting.

![image](https://user-images.githubusercontent.com/17926293/36148028-cd5d15f6-10ba-11e8-931b-5f34a656c6a3.png)

[New Round] Word 1: ﻒﻄﻌﻣ, Word 2: ﻒﻄﻌﻤﻟا
Common: ﻌْ, Uncommon: ـﺠ / ﺢْ / ﻬِ / ﺟْ / ـﻢ

**Comment by CatmanIta** [comment]
Resolved by filtering out words with articles for MakeFriends.
