### ISSUE TITLE
[Crash] Taking/Saving a photo crashes on iOS11

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#733]
1. Create a Demo Profile
2. Use the Debug Menu (triple click on the bottom-right corner) to add bones
3. Enter Antura Space and take a picture
4. The game crashes when you confirm the purchase and it tries to save it 
![image](https://user-images.githubusercontent.com/17926293/36322846-2bd42818-134f-11e8-9d73-66b933d0ba5e.png)

NOTE: we use an opensource plugin for the saving. @StefanoCecere can provide more details...

**Comment by StefanoCecere** [comment]
should be fixed by f7e779eb31eed2e0a5fa9273595637a8421e187d please test on ios11 devices
