### ISSUE TITLE
[Reserved Area] add Instagram and Twitter icon

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#741]
Add the missing social network links/icons (Twitter and Instagram) in the bottom right corner:
![image](https://user-images.githubusercontent.com/17926293/50693177-82c90000-1036-11e9-96d6-ba911f20204d.png)

PS: are we using Telegram or not? Should we keep or remove its icon?

**Comment by StefanoCecere** [comment]
what are these (Telegra mand Instagram) urls?

**Comment by FrancyCavallari** [comment]
the ones that appear in the website: http://www.antura.org/
https://www.instagram.com/anturagame/
https://twitter.com/AnturaGame

**Comment by FrancyCavallari** [comment]
We are now using Telegram, better remove the icon+link:
![image](https://user-images.githubusercontent.com/17926293/50957078-97394c80-14bd-11e9-88e5-bc827410b4a4.png)
