### ISSUE TITLE
[DebugMenu] Force JP does not move the current PS

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#745]
Force JP now unlocks all gifts correctly bu it does not update the current PS.
Better if we force also the update of the current PS.

**Comment by CatmanIta** [comment]
What do you mean? I tested it, and it goes back to the map, unlocking the max PS as well as placing Antura at the chosen PS. Is there anything I am missing?

**Comment by FrancyCavallari** [comment]
Maybe I made a mistake when testing it... now it seems to work fine.
I close the issue.
