### ISSUE TITLE
[Shop] Dragging icon is wrong

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#749]

**Comment by CatmanIta** [comment]
Old?

**Comment by FrancyCavallari** [comment]
Better check that the fix was done also here (Antura_Arabic) and not only on Antura_LearnEnglish

**Comment by CatmanIta** [comment]
I think it's: 5f576e4
"Fixed bug with shop icons disappearing."

I remember doing it here.

**Comment by CatmanIta** [comment]
Yes, it is that one

**Comment by FrancyCavallari** [comment]
I am testing today cloud build and I have the wrong icon (the last used one) when dragging the mountains, but it could be another bug

**Comment by CatmanIta** [comment]
I'll check

**Comment by FrancyCavallari** [comment]
The same happens with the woods (group of trees) icon: a wrong icon (the last used one) appears

**Comment by CatmanIta** [comment]
That was a new one, the previous one referred to icons being "empty". I fixed Forest and Mountain as well.
