### ISSUE TITLE
[Egg_BuildWord] the Ui should not cover the Letters

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#750]
Once a word a complete the Green Checkmark appears covering the LL...
![image](https://user-images.githubusercontent.com/17926293/51542521-bf309480-1e5b-11e9-9938-b3abc0f0e261.png)

... the Letters should not be covered to reinforce the learning!

**Comment by CatmanIta** [comment]
That is part of the GlobalUI. I added an optional parameter to it, so to not mess with other uses.

This fix is not present in the other repository, should I reproduce it there too?
